### ISSUE TITLE
Laravel cant' find class

### ISSUE THREAD

**Issue by loweoj** [Hedronium/SpacelessBlade#1]
Hi,
I think you have an error in your composer.json as you're autoloading from "solidew" namespace rather than "hedronium" in psr-4 settings.

**Comment by omranjamal** [comment]
Please use version `2.0.0` for **Laravel 5.1** or above.
Otherwise use version `1.0.3`. The versions prior to `1.0.3` seem to have this issue.

We're extremely sorry for for this callous mistake. It slipped beneath the radar when we were changing our vendor name and namespaces.
